@startuml
participant Sender

participant "Deposit Vault"
participant "Transaction Vault"
participant "QR Code"
participant Receiver


Sender -> "Deposit Vault" : Sends the USDC 
"Deposit Vault" -> "Transaction Vault" : Deducts Transaction Fees
activate "Deposit Vault"
"Deposit Vault" -> "QR Code": Generates link in form of QR Code
activate "QR Code"
"QR Code" -> Sender: QR Code is send to Sender to give to Receiver
Sender -> Receiver: QR Code is sent to receiver 
Receiver -> "QR Code": Receiver scans QR Code

"QR Code" -> "Deposit Vault": QR Code authenticates and \nauthorizes the funds to be moved to receiver.
deactivate "QR Code"
"Deposit Vault" -> Receiver: Send funds to receiver
deactivate "Deposit Vault"

@enduml
